spring:
  profiles:
    active: dev
  config:
    import: application-secret.yml
  datasource:
    url: jdbc:mariadb://localhost:3306/nalsee
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

cloud:
  aws:
    credentials:
      access-key: ${cloud.aws.credentials.access-key}
      secret-key: ${cloud.aws.credentials.secret-key}
    region:
      static: ap-northeast-2
    stack:
      auto: false

---
spring:
  config:
    activate:
      on-profile: prod
    import: application-prod.yml
---