spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/nalsee?useUnicode=true&characterEncoding=UTF-8
    username: groot
    password: 1234
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3dd4f833d984da38334cc5c01c23ed5b
            client-secret: Zpiomn48UR0T198uygxgsQkQ91kDCrUL
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

cloud:
   aws:
    credentials:
      access-key: AKIAXFE3K33TPGJQRC4M
      secret-key: 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

