spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://mariadb:3306/nalsee
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3dd4f833d984da38334cc5c01c23ed5b
            client-secret: Zpiomn48UR0T198uygxgsQkQ91kDCrUL
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
                - profile_nickname
                - account_email
                - profile_image
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account


cloud:
  aws:
    credentials:
      access-key: AKIAXFE3K33TPGJQRC4M
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

---
# spring:
#   config:
#     activate:
#       on-profile: dev
#     import: application-secret.yml
# logging:
#   level:
#     org:
#       springframework:
#         security: DEBUG
#       hibernate:
#         SQL: DEBUG
#         type:
#           descriptor:
#             sql: TRACE

---
spring:
  config:
    activate:
      on-profile: prod
    import: application-prod.yml
logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

---
# spring:
#   config:
#     activate:
#       on-profile: kram
#     import: application-kram.yml
# logging:
#   level:
#     org:
#       springframework:
#         security: DEBUG
#       hibernate:
#         SQL: DEBUG
#         type:
#           descriptor:
#             sql: TRACE
